// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6fGxzn6DuqOOFLdmqhhL1Fj1UUrMJvh4',
    appId: '1:920278341561:web:d409c399aed8b6216a8868',
    messagingSenderId: '920278341561',
    projectId: 'instagramapp-d3abb',
    authDomain: 'instagramapp-d3abb.firebaseapp.com',
    storageBucket: 'instagramapp-d3abb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATmPZiphoN_dtV4aK6ISGsrLegSn35b6Q',
    appId: '1:920278341561:android:21b575dbca8ece9c6a8868',
    messagingSenderId: '920278341561',
    projectId: 'instagramapp-d3abb',
    storageBucket: 'instagramapp-d3abb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIVN4RxVEE_OiV5NrIvwFz3ZiE_txpusc',
    appId: '1:920278341561:ios:58b2e2896c2737d36a8868',
    messagingSenderId: '920278341561',
    projectId: 'instagramapp-d3abb',
    storageBucket: 'instagramapp-d3abb.appspot.com',
    iosBundleId: 'com.example.instagramapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIVN4RxVEE_OiV5NrIvwFz3ZiE_txpusc',
    appId: '1:920278341561:ios:f150c57ba10381786a8868',
    messagingSenderId: '920278341561',
    projectId: 'instagramapp-d3abb',
    storageBucket: 'instagramapp-d3abb.appspot.com',
    iosBundleId: 'com.example.instagramapp.RunnerTests',
  );
}
